#!/bin/sh

CHALLENGE_ID=${CHALLENGE_ID}
SCORER_TYPE=${SCORER_TYPE}
SUBMISSION_ID=${SUBMISSION_ID}

java -Xms512M -Xmx512M -jar /app/java-scorer.jar $CHALLENGE_ID $SCORER_TYPE $SUBMISSION_ID
EXIT_CODE=$?

exit $EXIT_CODE 